//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodArkadasim.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public byte id { get; set; }
        public string GonderenKullanici { get; set; }
        public string AlanKullanici { get; set; }
        public string Aciklama { get; set; }
        public string Baslik { get; set; }
        public string GonderenAvatar { get; set; }
    }
}
