//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kodArkadasim.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.Fikirler = new HashSet<Fikirler>();
            this.Projeler = new HashSet<Projeler>();
        }
    
        public byte Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Gmail { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public string Rank { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Seviye { get; set; }
        public string Hakkimda { get; set; }
        public Nullable<byte> ProjeSayisi { get; set; }
        public string Avatar { get; set; }
        public Nullable<byte> FikirSayisi { get; set; }
        public string IsimSoyisim { get; set; }
        public string Meslek { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fikirler> Fikirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeler> Projeler { get; set; }
    }
}
